Ensure clang-18 explicitly installed

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -19,6 +19,17 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
+    - name: Set up clang
+      run: |
+        apt-get update
+        apt-get install -y --no-install-recommends clang-18
+        if command -v clang-18 &> /dev/null; then
+          echo "clang-18 installed successfully"
+        else
+          echo "clang-18 installation failed"
+          exit 1
+        fi
+
     - name: Set rustup version
       run: rustup default stable
     
